# Generated by Django 4.1.3 on 2022-11-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=50)),
                ('duration', models.TextField(max_length=500)),
                ('fees', models.TextField(max_length=500)),
            ],
        ),
    ]
